# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    container_name: crypto_bot_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8050:8050"  # Streamlit dashboard
      - "8888:8888"  # Jupyter Lab (optional)
    volumes:
      - ./src:/workspace/src
      - ./scripts:/workspace/scripts
      - ./tests:/workspace/tests
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./logs:/workspace/logs
    env_file:
      - .env
    command: bash /workspace/scripts/start.sh
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  db:
    image: postgres:15
    container_name: crypto_bot_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: